services:

  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: https://bus-ticketing-ouxm.onrender.com
        RESEND_API_KEY: your_resend_api_key_here
        KHALTI_SECRET_KEY: your_khalti_secret_key_here
    container_name: seat-sathi-web-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_BASE_URL=https://bus-ticketing-ouxm.onrender.com
      - RESEND_API_KEY=your_resend_api_key_here
      - KHALTI_SECRET_KEY=your_khalti_secret_key_here
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: seat-sathi-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: